In [1]:
import torch

In [1]:
import numpy as np


In [2]:
s = np.array([0, 1.2, 0.2, 0.3, 0.5])
y2 = 1
exp_s = np.exp(s)
probobility = exp_s[y2]/np.sum(exp_s)
print(exp_s,probobility)

[1.         3.32011692 1.22140276 1.34985881 1.64872127] 0.3887679320338663


In [3]:
np.sum(exp_s)

8.540099759172847

In [4]:
-np.log(probobility)

0.9447726891342243

In [45]:
linear = nn.Linear(3,4)
type(linear)

torch.nn.modules.linear.Linear

## torch.nn.Sequential

In [38]:
net = nn.Sequential(nn.Linear(3,2),nn.Linear(2,1))
for layer in net.children():
    print(layer)

Linear(in_features=3, out_features=2, bias=True)
Linear(in_features=2, out_features=1, bias=True)


In [39]:
layers = list(net.children())
first_layer = layers[0]

In [44]:
weight = first_layer.weight.data
bias   = first_layer.bias.data
print(weight)
print(bias)

tensor([[-3.9375e-04,  1.3928e-01,  3.0153e-01],
        [ 2.1260e-01, -8.1568e-02, -4.0216e-01]])
tensor([ 0.0680, -0.5656])


## torch.nn.Module

In [2]:
import torch.nn as nn

In [9]:
def init_weights(m):
    #print(m)
    if type(m)==nn.Linear:
        m.weight.data.fill_(1.0)
        print(m.weight)
net = nn.Sequential(nn.Linear(2,2),nn.Linear(2,2))
net.apply(init_weights)

Parameter containing:
tensor([[ 0.6749, -0.1854],
        [-0.2813,  0.3946]], requires_grad=True)
Parameter containing:
tensor([[ 0.6885, -0.5316],
        [ 0.4664,  0.0105]], requires_grad=True)


Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)

In [13]:
print(list(net.children()))

[Linear(in_features=2, out_features=2, bias=True), Linear(in_features=2, out_features=2, bias=True)]


In [15]:
for i in net.children():
    print(i)

Linear(in_features=2, out_features=2, bias=True)
Linear(in_features=2, out_features=2, bias=True)


In [27]:
for param in net.parameters():
    print(param.size())
    print(param.data)

torch.Size([2, 2])
tensor([[1., 1.],
        [1., 1.]])
torch.Size([2])
tensor([-0.2762,  0.5109])
torch.Size([2, 2])
tensor([[1., 1.],
        [1., 1.]])
torch.Size([2])
tensor([-0.5321, -0.3267])


In [25]:
type(net.parameters())

generator